export const SHOW_SETTINGS = "SHOW_SETTINGS";
export const HIDE_SETTINGS = "HIDE_SETTINGS";
export const SHOW_APPEND_MODAL = "SHOW_APPEND_MODAL";
export const HIDE_APPEND_MODAL = "HIDE_APPEND_MODAL";
export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const HIDE_EDIT_MODAL = "HIDE_EDIT_MODAL";

export const RENDER_ALL_COLORS = "RENDER_ALL_COLORS";
export const APPEND_NEW_COLOR = "APPEND_NEW_COLOR";
